### ISSUE TITLE
Missing tech dependency for aircraft energy shields

### ISSUE THREAD

**Issue by ST-DDT** [Stifling-Bossness/Aircraft#10]
IMO the aircraft energy shield should have a tech dependency on personal energy shields especially since it is required for crafting.
This also allows the user to see it early on that there is an extension for the shields when researching the personal energy shields.

Yes, I know that you will always have researched the PES long before the AES, but I would add it anyway for consistency reasons.

**Comment by Stifling-Bossness** [comment]
Set for 1.1.5, I forgot to check github for a while otherwise this would've been done a while ago.
