### ISSUE TITLE
Cargo Plane Does not have a weapon

### ISSUE THREAD

**Issue by Rovoska** [Stifling-Bossness/Aircraft#14]
It indicates that it should, but upon building one I found it lacking.

**Comment by Stifling-Bossness** [comment]
On my test save it has one, are you maybe using other mods that could override it?

**Comment by Rovoska** [comment]
base

aai-programmable-structures

aai-programmable-vehicles

aai-signals

aai-vehicles-chaingunner

aai-vehicles-flame-tank

aai-vehicles-flame-tumbler

aai-vehicles-hauler

aai-vehicles-laser-tank

aai-vehicles-miner

aai-vehicles-warden

aai-zones

Advanced-Solar

air-filtering

Aircraft

AutoDeconstruct

AutoTrash

bullet-trails

clock

data-raw-prototypes

detached-gun-sounds

ElectricFurnaces

FARL

FlowControl

LiftoffEnhanced

LoaderRedux

off-grid-effects

robotarmy

skan-advanced-mining

Warehousing

YARM

**Comment by Rovoska** [comment]
Those are what I'm using.
