### ISSUE TITLE
Failed to load modifications  'heli-technology'

### ISSUE THREAD

**Issue by Tomirad** [Stifling-Bossness/Aircraft#16]
`Mods to disable: Failed to load modifications: __Aircraft__/data-updates.lua:96: attempt to index field 'heli-technology' (a nil value)`
After  check option in settings mods, I have this error.

Also too:
`Mods to disable: Failed to load modifications: __Aircraft__/data-updates.lua:100: attempt to index field 'raven' (a nil value)`

**Comment by Stifling-Bossness** [comment]
This may seem like a stupid question, but do you have the 2 other mods installed?

**Comment by Tomirad** [comment]
No, I have only one mod. 
I specifically checked whether I have no duplicates. And similar mods.

The problem is solved when I manually remove this keys from the mod settings. (.json)
