### ISSUE TITLE
Suggestion: Change balancing to be more realistic (crafting)

### ISSUE THREAD

**Issue by ST-DDT** [Stifling-Bossness/Aircraft#18]
IMO the recipes for aircraft are crafted way to fast.

* aircraft equipment should at least take 10 seconds to be crafted each. 
* Also the aircraft energy shield should take more batteries because that is quite cheap in comparison with the processors from MK2. Maybe 250 batteries would be a good value.
* The airplanes should take 30 seconds to be crafted and the flying fortress 60 seconds (you only need very few of them anyway)
* maybe the airplanes should be moved to the logistics tab since the other vehicles are there as well
* the highly explosive canon ammo needs some tweaks, as it looks like it is more explosive/damaging than the uranium version, maybe the recipe could be removed altogether, due to the other alternatives
* i cannot find a difference between napalm and the vanilla flame-thrower ammo (damage). Maybe this needs to be buffed a little. (and it is also too fast to be crafted)

**Comment by Stifling-Bossness** [comment]
Hey, did quite a few of these little tweaks in 1.4.5, although not quite so drastic as suggested. I'll admit that I overlooked these for quite a while, but tell what you think!

**Comment by ST-DDT** [comment]
The reordering and the crafting times look good to me.
Thanks for addressing this issue that fast.

Maybe I'm just a little nit picky there, but the high-explosives are still more dangerous than  the nuclear variants.

![explosive](https://user-images.githubusercontent.com/1579362/34578578-c4f85d7a-f185-11e7-898c-aaba35e67da3.png)
![high-explosive](https://user-images.githubusercontent.com/1579362/34578583-c7cb0098-f185-11e7-90c1-825162771854.png)
![nuclear-explosive](https://user-images.githubusercontent.com/1579362/34578584-ca1ad396-f185-11e7-8890-fd8b520b659b.png)

This small difference has actually a large impact on the damage dealt.

With canon research 6 here is the damage dealt to a rocket-silo:

* explosive: 4244/5000 (756 damage -> 7 shots)
* high-explosive; 2480/5000 (2520 damage -> 2 shots)
* nuclear-explosive: 3530/5000 (1470 damage -> 4 shots)

also the increased damage radius further harms the balance. 

Maybe you should also add nuclear-high- explosive ammo which would virtually decouple the comparison.
