### ISSUE TITLE
Game crashes when in aircraft and you cancel your current research

### ISSUE THREAD

**Issue by zerocool444** [Stifling-Bossness/Aircraft#34]
Factorio seems to crash when you are in your aircraft or out of it and cancel the current research.  I have research queue turned on in my map.  It does not crash if you cancel the queued research, just the active research.

**Comment by Stifling-Bossness** [comment]
This is a base game bug

https://forums.factorio.com/viewtopic.php?f=7&t=66301
https://forums.factorio.com/viewtopic.php?f=7&t=66389
https://forums.factorio.com/viewtopic.php?f=7&t=66367
https://forums.factorio.com/viewtopic.php?t=66233

Only solution right now is to wait for the next official release and hope they've fixed it. Thanks for submitting a report anyways. In the future, crash logs are immensely helpful when reporting a crash.

**Comment by Stifling-Bossness** [comment]
Fixed in Factorio .17.5

https://forums.factorio.com/viewtopic.php?f=3&t=66705
