### ISSUE TITLE
Please add no-automated-item-removal to all fighter jet class planes

### ISSUE THREAD

**Issue by AlienXAXS** [Stifling-Bossness/Aircraft#35]
In 0.17 _no-automated-item-removal_ and _no-automated-item-insertion_ was put in as prototype flags. 

While flying over my base in either fighter-classed planes (Flying Fortress or the Gunship) and having its fuel taken out of it or random stuff shoved into it has caused some issues in the past with random items being placed on belts for example.

Because of this, I ask if it's possible for you to also add the flags "no-automated-item-removal" (and maybe "no-automated-item-insertion") into these vehicles?

Many thanks,
AlienX

**Comment by Stifling-Bossness** [comment]
I thought I already added those, but it seems I got lost along the way while testing them out. Thanks for the reminder.

**Comment by Stifling-Bossness** [comment]
Turns out I _did_ already do it, I just forgot it's a setting. Try turning on "inserter immunity" in your mod settings.
