### ISSUE TITLE
Planes getting destroyed almost instantly by acid

### ISSUE THREAD

**Issue by JaJe92** [Stifling-Bossness/Aircraft#39]
**What is the bug?**
Plane getting destroyed almost instanly by flying over the acid

**How do I make it happen?**
let a group of spitters stain a small area with acid then fly above to get damage from acid until it get destroyed.

**What's supposed to happen instead?**
Nothing, not receiving any damage, but only if the plane is directly hit by acid.

**Screenshots/Videos**
Screenshots and/or videos are helpful in situations where it's a graphical bug, or if you can't copy/paste text directly from the source. You can host them using a site like imgur.com.

**Versions**
 - Operating System: Win10 x64 v.1903
 - Factorio Version: 0.17.52
 - Mod Version: 1.6.6

**Extra Info**
I noticed this issue with my Jet plane and having a shield incorporated + 2 extra afterburners.

**Comment by Stifling-Bossness** [comment]
Added a new setting to globally disable acid splash puddle damage. I couldn't find a way to negate the damage properly, since I couldn't _find_ the damage.
