### ISSUE TITLE
Can't see battery level

### ISSUE THREAD

**Issue by Redstylt** [Stifling-Bossness/Aircraft#45]
**What is the bug?**
We can't see the battery level next to the vehicule

**How do I make it happen?**
When batteries are in the grid

**What's supposed to happen instead?**
See the battery level like it happens with a suit

**Screenshots/Videos**
https://imgur.com/a/c0y9d3V

**Versions**
 - Operating System: w10
 - Factorio Version: 17.69
 - Mod Version: 1.6.12 + IR  0.99.7

**Extra Info**

**Comment by Stifling-Bossness** [comment]
Can you see the battery meter on any vehicle with an equipment grid? It might be a suit-only thing.

**Comment by snouz** [comment]
Probably part of a past factorio update, you can see the battery level next to the icon now.
