### ISSUE TITLE
Bug? Burning time of napalm is the same as that of regular ammo 

### ISSUE THREAD

**Issue by saaadel** [Stifling-Bossness/Aircraft#48]
**What's your idea?**
Bug? Burning time of napalm is the same as that of regular ammo.
But it costs x4 of regular ammo. Lets it burn x4 time (or more).

**Comment by saaadel** [comment]
I am playing with AAI

**Comment by snouz** [comment]
I've completely rehauled napalm (visually and gameplay) in 1.8. It was indeed using old parameters removed from factorio, and thus the differences were completely ignored by the game.
