### ISSUE TITLE
It says that the mod is incompatible with my game version

### ISSUE THREAD

**Issue by DraigCore** [Stifling-Bossness/Aircraft#49]
**What is the bug?**
![Bug report](https://user-images.githubusercontent.com/77800465/105390077-0ab6de00-5bef-11eb-8442-e36974b71de4.png)
i downloaded it from here as the 29 August 2020 release
**Versions**
 - Operating System: Windows 10
 - Factorio Version: 1.1.12

**Comment by Stifling-Bossness** [comment]
you're using 1.7.1 not 1.7.2, update to latest version

**Comment by DraigCore** [comment]
oh i see... so, i downloaded the last release on this source
