### ISSUE TITLE
Energy shield causes an error

### ISSUE THREAD

**Issue by FranciscoMeggi** [Stifling-Bossness/Aircraft#50]
**What is the bug?**
The energy shields makes an error to appear

**How do I make it happen?**
Using a energy shield on the aircraft

**What's supposed to happen instead?**
The error not happening

**Screenshots/Videos**
Screenshots and/or videos are helpful in situations where it's a graphical bug, or if you can't copy/paste text directly from the source. You can host them using a site like imgur.com.
Image:
https://imgur.com/a/sjc9yPA

**Versions**
 - Operating System:W10
 - Factorio Version:1.1.37
 - Mod Version:1.3.1

**Extra Info**

**Comment by FranciscoMeggi** [comment]
Update energy shield is not the problem.
I have no idea now what the problem can be

**Comment by FranciscoMeggi** [comment]
Found the problem.
I can't take off/lan with things on the grid area (ex. afterburner, solar panels, batteries or enrgy shield).
But if I put them after the take off and took them before landing there is no problem at all.

**Comment by Stifling-Bossness** [comment]
Issue with [Aircraft Realism](https://mods.factorio.com/mod/AircraftRealism), not aircraft.
