### ISSUE TITLE
Please add an option to mute the jet sound

### ISSUE THREAD

**Issue by JasonLandbridge** [Stifling-Bossness/Aircraft#58]
**What's your idea?**

An option to mute the sounds of the jet, it's incredibly annoying when you use it to constantly to move around

**Do you have any other options or variations you've considered?**

**Mock-up art**
You can post images, videos, or anything else here to help visualize your point. You can use a site like imgur.com to host them.

**Comment by Stifling-Bossness** [comment]
Probably not gonna add an all-out mute option, but there already exists an option "Use aircraft sounds" that will revert our custom sound to the default Factorio car sound.
