### ISSUE TITLE
grid for the military equipment

### ISSUE THREAD

**Issue by AMAURY-Emilien** [Stifling-Bossness/Aircraft#60]
Hello I play with Krastorio2 and AAI Industry, and the first one divide by 2 the grid for the military equipment. 
And that provoque a problem that did (screenshoot)
![probleme](https://github.com/Stifling-Bossness/Aircraft/assets/115998830/543a0563-7f9a-427b-8016-935b8ac4fee8)
 I had allrady put this in the github's Krastorio2 but I havn't get an answer so may could you put en option for choose the size of military equipment. Even if, I will modify (just for mytself and will not put in on internet) manually for the the option directly into the code ( a simply fork just for me).

**Comment by Stifling-Bossness** [comment]
Hey, thanks for filling out a report, but this seems to be an issue with K2. I'm not doing much for this mod anymore other than basic upkeep, but [Krastorio 2 Compat](https://mods.factorio.com/mod/krastorio-2-compat) appears to return the grid to normal size if I'm reading the data-final-fixes correctly.

I've never done much with K2, so I'm afraid that's about all the help I'm going to be able to give on it.
