### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by argon1321** [Stifling-Bossness/Aircraft#66]
**What is the bug?**
![image](https://github.com/user-attachments/assets/8fd521e7-9db8-490d-82f0-380f2e685122)

**How do I make it happen?**
Try flying a jet with these mods.
![image](https://github.com/user-attachments/assets/c62762c2-691c-42b9-aa4e-77d83d32e1ed)

**What's supposed to happen instead?**
No crashes.
**Screenshots/Videos**
Screenshots and/or videos are helpful in situations where it's a graphical bug, or if you can't copy/paste text directly from the source. You can host them using a site like imgur.com.

**Versions**
 - Operating System: Win 11
 - Factorio Version: 2.0.28
 - Mod Version: 2.2.0

**Extra Info**
pls fix

**Comment by Stifling-Bossness** [comment]
1) this isn't the repository for the space age aircraft fork.
2) the error is in aircraft realism, not aircraft.
3) 'pls fix' -_-
