### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by petergaultney** [Stifling-Bossness/Aircraft#7]
I'm not sure what the license for this mod is, and it would be helpful to have the license in a LICENSE file as is standard practice.

I'd like to fork this and make a pull request to make it work for 0.14, but I am not sure whether forking would constitute illegal distribution.

Thanks!

**Comment by Stifling-Bossness** [comment]
The most up-to-date version is already updated to 0.14, I can't upload to the mod portal because I haven't bought the game. Newest versions are posted to https://forums.factorio.com/viewtopic.php?f=120&t=18714
